//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Area 的當地語系化字串。
        /// </summary>
        internal static string ButtonArea {
            get {
                return ResourceManager.GetString("ButtonArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Black background 的當地語系化字串。
        /// </summary>
        internal static string ButtonBackGround {
            get {
                return ResourceManager.GetString("ButtonBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Distance 的當地語系化字串。
        /// </summary>
        internal static string ButtonDistance {
            get {
                return ResourceManager.GetString("ButtonDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fit to window 的當地語系化字串。
        /// </summary>
        internal static string ButtonFitToWindow {
            get {
                return ResourceManager.GetString("ButtonFitToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download CSV 的當地語系化字串。
        /// </summary>
        internal static string ButtonGetCSV {
            get {
                return ResourceManager.GetString("ButtonGetCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Info 的當地語系化字串。
        /// </summary>
        internal static string ButtonInfo {
            get {
                return ResourceManager.GetString("ButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Layers 的當地語系化字串。
        /// </summary>
        internal static string ButtonLayers {
            get {
                return ResourceManager.GetString("ButtonLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load from HDD 的當地語系化字串。
        /// </summary>
        internal static string ButtonLoadFromHDD {
            get {
                return ResourceManager.GetString("ButtonLoadFromHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load from Web 的當地語系化字串。
        /// </summary>
        internal static string ButtonLoadFromWeb {
            get {
                return ResourceManager.GetString("ButtonLoadFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Orbit 的當地語系化字串。
        /// </summary>
        internal static string ButtonOrbit {
            get {
                return ResourceManager.GetString("ButtonOrbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Polyline 的當地語系化字串。
        /// </summary>
        internal static string ButtonPolyline {
            get {
                return ResourceManager.GetString("ButtonPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Print 的當地語系化字串。
        /// </summary>
        internal static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Zoom in 的當地語系化字串。
        /// </summary>
        internal static string ButtonZoomIn {
            get {
                return ResourceManager.GetString("ButtonZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Zoom out 的當地語系化字串。
        /// </summary>
        internal static string ButtonZoomOut {
            get {
                return ResourceManager.GetString("ButtonZoomOut", resourceCulture);
            }
        }
    }
}
